apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: onnxmodel
    serving.kserve.io/deploymentMode: ModelMesh
  name: onnxmodel
  namespace: rhods-project
  labels:
    name: onnxmodel
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: onnx
        version: '1'
      runtime: model-server
      storage:
        key: aws-connection-ionos
        path: models/onnx_model_inference.onnx