apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    openshift.io/display-name: tf-model-lstm
    serving.kserve.io/deploymentMode: ModelMesh
  name: tf-model-lstm
  namespace: rhods-project
  labels:
    name: tf-model-lstm
    opendatahub.io/dashboard: 'true'
spec:
  predictor:
    model:
      modelFormat:
        name: tensorflow
        version: '1'
      runtime: model-server
      storage:
        key: aws-connection-ionos
        path: models/