apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: pyspark-small
  namespace: sales-challenge
spec:
  version: "1.0"
  sparkImage: image-registry.openshift-image-registry.svc:5000/sales-challenge/pyspark:latest
  mode: cluster
  mainApplicationFile: local:///stackable/spark/main_spark_lstm.py
  driver:
    resources:
      cpu:
        max: "3"
      memory:
        limit: "4Gi"
  executor:
    instances: 1
    resources:
      cpu:
        min: "1"
        max: "1"
      memory:
        limit: "1Gi"